### ISSUE TITLE
Issue during compilation

### ISSUE THREAD

**Issue by datavici** [SensESP/NMEA0183#3] opened 2022-10-28 18:43 UTC
It  appears compiling the GPS example (converting it to main.cpp) as is creates an issue as defined below when building in platform.io once it starts to link firmware.elf.  It references an issue with postion.h, specifically with the JSON conversion, citing multiple definitions.  Error below.  Unsure where to troubleshoot.

c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb07\libNMEA0183.a(nmea0183.cpp.o): in function `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: multiple definition of `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb07\libNMEA0183.a(nmea0183.cpp.o): in function `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: multiple definition of `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb07\libNMEA0183.a(nmea_parser.cpp.o): in function `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: multiple definition of `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb07\libNMEA0183.a(nmea_parser.cpp.o): in function `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: multiple definition of `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb07\libNMEA0183.a(wiring.cpp.o): in function `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: multiple definition of `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb07\libNMEA0183.a(wiring.cpp.o): in function `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: multiple definition of `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb72\libSensESP.a(signalk_position.cpp.o): in function `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: multiple definition of `sensesp::canConvertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position const&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:69: first defined here
c:/users/mikeh/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\libb72\libSensESP.a(signalk_position.cpp.o): in function `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)':
C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: multiple definition of `sensesp::convertFromJson(ArduinoJson6194_F1::VariantConstRef, sensesp::Position&)'; .pio\build\esp32dev\src\main.cpp.o:C:\Users\mikeh\OneDrive\Documents\SensESP-project-template-main\SensESP-project-template-main/.pio/libdeps/esp32dev/SensESP/src/sensesp/types/position.h:49: first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1

**Comment by ali69si** [comment] 2022-12-26 10:11
Having the same problem here. Have you found a solution?

**Comment by g0kad** [comment] 2024-01-01 15:45
Same issue here.  I hope there is a solution.

**Comment by grhitch** [comment] 2024-01-05 22:26
I have the same problem and have made a change to position.h in  Signalk/sensesp to inline the definitions of ConvertFromJson  and CanConvertFromJson. The changes are as follows:
`49 - void convertFromJson(JsonVariantConst src, Position &dst) {
49 + inline void convertFromJson(JsonVariantConst src, Position &dst) {
  
69 - bool canConvertFromJson(JsonVariantConst src, const Position &) {
69 + inline bool canConvertFromJson(JsonVariantConst src, const Position &) {`

Care also needs to be taken to ensure that ArduinoJSON is version 6.x.x and not 7.0.0

I am still working on this to see if I can propose a PR that addresses this. 

There is a conversation on Slack in the SignalK #sensors channel

**Comment by grhitch** [comment] 2024-01-07 02:22
Ok, I refreshed my fork of SensESP and made changes using in-lining. This allows compiling and linking. I then set up a cpp and moved the function definitions there. Now that I would like to test it, I cannot find these functions used anywhere in sensESP.

I see that this functionality was added in [https://github.com/SignalK/SensESP/pull/614](url).

Not knowing if anybody is dependent on this code, it would be a bit harsh to just remove the functions, even though that seems like the best solution to me.

**Comment by mairas** [comment] 2024-01-07 12:12
I believe the root cause is actually the just-released ArduinoJson 7 that has some breaking changes (as major versions tend to do). Since ArduinoJson version was not pegged in SensESP, this broke not just NMEA 0183 but also SensESP builds.

The original reported issue here might be something different. Let's see if it still exists once I've released a fixed SensESP version.

**Comment by mairas** [comment] 2024-01-07 15:05
I believe the issue has now been fixed; the root cause was that `convertFromJson` can `canConvertFromJson` functions were defined in the header file. This breaks the compilation if the header is included in more than a single place. Apologies for not noticing this issue earlier!

You might need to delete the `.pio` folder in your project to force PlatformIO to update all libraries. After that, the project should build fine.

I'll close this issue once someone verifies that the problem has been fixed.

**Comment by g0kad** [comment] 2024-01-07 20:45
Issue fixed here.  Everything compiles well.  Now to add some parsers to my GNSS project.  Thanks to mairas for the fix.

**Comment by mairas** [comment] 2024-01-07 20:47
Great, thanks a bunch for verifying!

**Closed by mairas** 2024-01-07 20:47 UTC
